export const REDUCER_SAVE_CHANGE_PASSWORD_STATE = 'REDUCER_SAVE_CHANGE-PASSWORD_STATE';
export const REDUCER_SAVE_LOGIN_STATE = 'REDUCER_SAVE_LOGIN_STATE';
export const REDUCER_SAVE_REGISTRATION_STATE = 'REDUCER_SAVE_REGISTRATION_STATE';
export const SAGA_CHANGE_PASSWORD_REQUEST = 'SAGA_CHANGE_PASSWORD_REQUEST';
export const SAGA_REGISTRATION_REQUEST = 'SAGA_REGISTRATION_REQUEST';
export const SAGA_LOGIN_REQUEST = 'SAGA_LOGIN_REQUEST';