export const REDUCER_SAVE_CHANGE_PASSWORD_STATE = 'REDUCER_SAVE_CHANGE-PASSWORD_STATE';
export const REDUCER_SAVE_LOGIN_STATE = 'REDUCER_SAVE_LOGIN_STATE';
export const REDUCER_SAVE_REGISTRATION_STATE = 'REDUCER_SAVE_REGISTRATION_STATE';